Add Support for Creating Azure Credential Internally
Azure/azure-schema-registry-for-kafka pull request #60
Opened 2024-12-04 22:45 UTC by nickghardwick

This PR addresses an issue with the configuration of the Azure Schema Registry Kafka Avro package where a `TokenCredential` was required to be generated before passing into the serializer. Some environments, such as Java Spring, cannot directly pass in credentials as thier config files only accept strings as input. This address this pitfall but adding a check for creating the `DefaultAzureCredential` in the library itself if a token credential cannot be provided in the configuration steps.

2025-01-22 01:44 UTC, hmlam requested changes

2025-01-22 01:44 UTC, hmlam commented on java/avro/src/main/java/com/microsoft/azure/schemaregistry/kafka/avro/KafkaAvroSerializer.java
> +        } else {
won't this means that if tokenCredential is not null to begin with we end up throwing RuntimeException?

2025-01-22 01:44 UTC, hmlam commented on java/avro/src/main/java/com/microsoft/azure/schemaregistry/kafka/avro/KafkaAvroDeserializer.java
> +        } else {
won't this means that if tokenCredential is not null to begin with we end up throwing RuntimeException?

2025-03-11 21:33 UTC, hmlam requested changes

2025-03-11 21:33 UTC, hmlam commented on java/avro/src/main/java/com/microsoft/azure/schemaregistry/kafka/avro/AbstractKafkaSerdeConfig.java
> +    public static final String CREATE_DEFAULT_AZURE_CREDENTIAL = "create.default.azure.credential";
Let's call this use.azure.credential

2025-03-11 21:33 UTC, hmlam commented on java/avro/samples/kafka-consumer/pom.xml
> +      <version>1.1.0-beta.2</version>
As part of the change, let's add the SpringBoot sample as well. basically have one extra sample that based on the current simple produce/fetch but through https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/authentication way of auth.

2025-03-18 04:43 UTC, nickghardwick commented on java/avro/samples/spring-sample/src/main/java/com/microsoft/azure/azure_schemaregistry_avro_spring_sample/AppConfig.java
> +	public String buildJaasConfig() {
The need for the Azure Credential is for the schema registry library to authenticate with Event Hubs to have access to schema resources. This config is for the Event Hubs Kafka library to send and receive message that the schema registry library deserializes. All props to configure the both the Kafka library to communicate with Event Hubs and the schema registry library are passed in the `application.props` file, which only accepts strings as values.

2025-03-18 21:17 UTC, hmlam approved these changes

2025-03-18 21:17 UTC, merged